DROP TABLE IF EXISTS roles CASCADE;


DROP TABLE IF EXISTS "Roles" CASCADE;


DROP TABLE IF EXISTS bridge_project_profiles CASCADE;


DROP TABLE IF EXISTS groups CASCADE;


DROP TABLE IF EXISTS "Groups" CASCADE;


DROP TABLE IF EXISTS projects CASCADE;


DROP TABLE IF EXISTS "UsersToProjects" CASCADE;


DROP TABLE IF EXISTS "Projects" CASCADE;


DROP TABLE IF EXISTS users CASCADE;


DROP TABLE IF EXISTS "Users" CASCADE;


DROP TABLE IF EXISTS "user";


DROP TABLE IF EXISTS users_group_id__groups CASCADE;