DROP TABLE IF EXISTS roles CASCADE;


DROP TABLE IF EXISTS users_to_projects CASCADE;


DROP TABLE IF EXISTS users_to_groups CASCADE;


DROP TABLE IF EXISTS groups CASCADE;


DROP TABLE IF EXISTS projects CASCADE;


DROP TABLE IF EXISTS users CASCADE;